name: Publish Modules

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Whether this release is a prerelease'
        default: 'true'
        required: true

jobs:
  publish:
    name: Build modules and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'

      - name: Git Version
        uses: codacy/git-version@2.5.3
        id: version
        with:
          release-branch: main
          log-paths: ./

      # Base64 decodes and pipes the GPG key content into the secret file
      - name: Prepare environment
        env:
          GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        run: sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"

      - name: Publish modules
        run: ./gradlew  publishToSonatype --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          VERSION: ${{ steps.version.outputs.version }}

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.version.outputs.version }}
          message: 'Version ${{ steps.version.outputs.version }}'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          stripHeaders: true
          releaseBranch: "main"
          pullRequests: true
          author: true
          issues: true
          issuesWoLabels: true
          prWoLabels: true
          compareLink: true
          filterByMilestone: false
          unreleased: false
          onlyLastTag: true

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          commit: ${{ env.GITHUB_SHA }}
          tag: ${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ github.event.inputs.prerelease }}
