name: Quality Checks

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'changelogs/**'
      - '**.md'
      - '.github/*.yml'

jobs:
  assemble:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Build
        run: bash ./gradlew assemble --stacktrace

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Unit tests
        run: bash ./gradlew :tts-ktx:test --stacktrace
      - uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: Unit test results
          path: ./**/build/reports/tests/
          if-no-files-found: ignore

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    needs: assemble
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: 11
          cache: 'gradle'
      - name: Run detekt
        run: bash ./gradlew detekt
      - name: Run Lint
        run: bash ./gradlew lint
      - uses: yutailang0119/action-android-lint@v2
        if: ${{ always() }}
        continue-on-error: true
        with:
          xml_path: tts-ktx/build/reports/lint-results-debug.xml